/**
 * Tiny client-side helpers for firing Meta Pixel events. Type-safe
 * wrapper around `window.fbq` that no-ops when fbq isn't loaded
 * (e.g. ad-blockers, no Pixel ID configured for this course, SSR).
 *
 * Server-side mirror of these events lives in `lib/meta-capi.ts`.
 * Both share the same `event_id` (generated by callers) so Meta
 * deduplicates browser + server hits for the same conversion.
 */

declare global {
  interface Window {
    fbq?: (...args: unknown[]) => void;
  }
}

export type PixelEvent =
  | 'PageView'
  | 'Lead'
  | 'InitiateCheckout'
  | 'AddToCart'
  | 'Purchase'
  | 'CompleteRegistration'
  | 'Contact'
  | 'Subscribe';

export interface PixelEventParams {
  /** Total monetary value of the event. */
  value?: number;
  /** ISO 4217 currency code, e.g. 'USD'. Required when `value` is set. */
  currency?: string;
  /** Course slug or product ID(s). */
  content_ids?: string[];
  /** Human course/product name. */
  content_name?: string;
  /** 'product' for single SKUs, 'product_group' for bundles. */
  content_type?: 'product' | 'product_group';
  /** Free-form tag (e.g. 'Mentorship', 'Accelerator'). */
  content_category?: string;
  /** Number of items (defaults to 1). */
  num_items?: number;
}

/**
 * Fire a Pixel event. Pass `eventId` to mirror the same hit on CAPI
 * server-side under the same identity (Meta dedupes them).
 */
export function trackPixelEvent(
  event: PixelEvent,
  params: PixelEventParams = {},
  eventId?: string,
): void {
  if (typeof window === 'undefined') return;
  const fbq = window.fbq;
  if (!fbq) return; // ad-blocker, or pixel not loaded for this page
  try {
    fbq('track', event, params, eventId ? { eventID: eventId } : undefined);
  } catch {
    /* no-op */
  }
}

/**
 * Generate a UUID-like event_id usable for client/server dedup. Uses
 * crypto.randomUUID when available, falls back to a sufficient random
 * string otherwise.
 */
export function generateEventId(): string {
  if (typeof crypto !== 'undefined' && 'randomUUID' in crypto) {
    return crypto.randomUUID();
  }
  return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 14)}`;
}
