'use client';

import Script from 'next/script';
import { useEffect } from 'react';
import type { PixelEvent, PixelEventParams } from '@/lib/meta-pixel';

/**
 * Drops the Meta Pixel base code on any page tied to a course and fires
 * a `PageView` once the script is ready. Pure no-op when `pixelId` is
 * null/empty — admin courses without a configured Pixel ID don't ship
 * any third-party JS.
 *
 * Per-course Pixel IDs are passed in by server components that already
 * loaded the Course row (so we don't double-fetch). The loader is safe
 * to mount multiple times — fbq's own `init` is idempotent per pixel.
 *
 * Optionally fires a second conversion event (InitiateCheckout / Purchase)
 * on mount via `additionalEvent`. Lead events fire from inside the form
 * submit handler (not here) since they're action-triggered, not view-
 * triggered.
 */
interface MetaPixelLoaderProps {
  pixelId?: string | null;
  /**
   * Optional event_id to use for the auto PageView so server-side CAPI
   * can dedupe. Generated by callers that also fire CAPI server-side.
   * Most pages can omit it — PageView is rarely deduplicated for ROAS
   * since it doesn't optimize ad delivery.
   */
  pageViewEventId?: string;
  /**
   * Optional second event to fire alongside the auto PageView. Used by
   * /checkout (InitiateCheckout) and /checkout/success (Purchase) to
   * fire their conversion event the same instant the page mounts —
   * server-side CAPI mirrors fire from the corresponding webhook so
   * eventId should be the same string for proper dedup.
   */
  additionalEvent?: {
    event: PixelEvent;
    params?: PixelEventParams;
    eventId?: string;
  };
}

export function MetaPixelLoader({ pixelId, pageViewEventId, additionalEvent }: MetaPixelLoaderProps) {
  useEffect(() => {
    if (!pixelId) return;
    if (typeof window === 'undefined') return;
    // The base script's auto PageView only runs once per pixel init. On
    // client-side route changes (Next App Router), we want a fresh
    // PageView so each landing reads as a separate funnel touch. fbq
    // handles its own queue if the script hasn't loaded yet.
    const fire = () => {
      const fbq = (window as unknown as { fbq?: (...a: unknown[]) => void }).fbq;
      if (!fbq) return;
      try {
        fbq('track', 'PageView', {}, pageViewEventId ? { eventID: pageViewEventId } : undefined);
        if (additionalEvent) {
          fbq(
            'track',
            additionalEvent.event,
            additionalEvent.params ?? {},
            additionalEvent.eventId ? { eventID: additionalEvent.eventId } : undefined,
          );
        }
      } catch {
        /* no-op */
      }
    };
    // Defer one tick so the script has loaded if it's on the same render.
    const t = setTimeout(fire, 50);
    return () => clearTimeout(t);
  }, [pixelId, pageViewEventId, additionalEvent]);

  if (!pixelId) return null;

  // Important: `autoConfig: false` so we have explicit control over
  // PageView firing (and don't get a phantom PageView on every init).
  // The `noscript` <img> ensures users with JS disabled still register
  // a PageView pixel impression.
  return (
    <>
      <Script id={`meta-pixel-${pixelId}`} strategy="afterInteractive">
        {`!function(f,b,e,v,n,t,s)
{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};
if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];
s.parentNode.insertBefore(t,s)}(window, document,'script',
'https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '${pixelId}', {}, { autoConfig: false });`}
      </Script>
      <noscript>
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          height="1"
          width="1"
          style={{ display: 'none' }}
          alt=""
          src={`https://www.facebook.com/tr?id=${pixelId}&ev=PageView&noscript=1`}
        />
      </noscript>
    </>
  );
}
